spring:
  mail:
    #配置发送方协议
    protocol: smtp
    #配置smtp服务器地址
    host: smtp.sina.cn
    username: xlgfwb@sina.cn
    password: qwert1358
dubbo:
  application:
    name: emailService
  registry:
    address: zookeeper://192.168.191.191:2181
  protocol:
    port: -1
  consumer:
    check: false
