server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///touser
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  consumer:
    check: false
  application:
    name: UserService
  registry:
    address: zookeeper://192.168.191.191:2181
  protocol:
    port: -1